theme = "vienna"
baseurl = "http://blog.rudolph-miller.com/"
languageCode = "ja-JP"
title = "(rudolph-miller)"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2015 Rudolph Miller"

[params]
  twitter = "Rudolph_Miller"
  github = "Rudolph-Miller"
  ga_api_key = "UA-47602577-2"
  author = "Rudolph Miller"
  avatar = "/images/logo.png"
  contact = "mailto:lisper@rudolph-miller.com"
  bio = "Common Lisp Player."
  subtitle = "think, think and think."
  wishlist = "A3RNOUU855C76"
  # themecolor = "#hexcolor"
[permalinks]
  post = "/:year/:month/:day/:slug/"
