theme = "vienna"
baseurl = "http://blog.rudolph-miller.com/"
languageCode = "ja-JP"
title = "(rudolph-miller)"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2015 Rudolph Miller"

[params]
  twitter = "Rudolph_Miller"
  github = "Rudolph-Miller"
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"
  author = "Rudolph Miller"
  avatar = "/images/logo.png"
  contact = "mailto:lisper@rudolph-miller.com"
  bio = "Common Lisp Player."
  subtitle = "think, think and think."
  wishlist = "A3RNOUU855C76"
  # themecolor = "#hexcolor"
