baseurl = "http://blog.rudolph-miller.com/"
languageCode = "ja-JP"
title = "(rudolph-miller)"
copyright = "&copy; Copyright 2015 Rudolph Miller"

[params]
  twitter = "Rudolph_Miller"
  github = "Rudolph-Miller"
  ga_api_key = "UA-47602577-2"
  author = "Rudolph Miller"
  avatar = "/images/logo.png"
  contact = "mailto:lisper@rudolph-miller.com"
  bio = "Common Lisp Player."
  subtitle = "NO LISP, NO LIFE."
  wishlist = "A3RNOUU855C76"
  disqusshortname = "rudolph-miller"
[permalinks]
  post = "/:year/:month/:day/:slug/"
  slide = "/slide/:year/:month/:day/:slug/"
